### ISSUE TITLE
Support for Rotary Axis

### ISSUE THREAD

**Issue by ghost** [openhardwarecoza/LaserWeb2#45]
Transfer from https://github.com/openhardwarecoza/LaserWeb/issues/93

**Comment by cojarbi** [comment]
Ive built a rotary and off course i could use the Y axis, change the steps accordingly and use it that way but that defeats the point in LW.

Have you thought how to accomplish this? maybe: Create a selection to use Rotary then Generate code for X,Y but Y will be transformed into Extruder A maybe? I could edit the actual gcode and instead of Y can i use E?
